version: '3'
services:
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - .:/bitrise/go/src/github.com/slapec93/bitrise-attendance
    ports:
      - "3011:3001"
    links:
      - db:postgres
    environment:
      PORT: 3001
      IS_USE_GIN: "yes"
      DB_HOST: postgres
      DB_USER: postgres
      DB_PSW: postgres
      DB_NAME: bitriseattendancetest
      DB_SSL_MODE: disable